import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

export type CompoundFunctionClass =
  | "repair"
  | "metabolic"
  | "growth"
  | "performance"
  | "aesthetic";

export type LibrarySourceStatus = "seed" | "imported";
export type PharmacokineticConfidence = "exact" | "estimated" | "unknown";

export interface SeedLibraryEntry {
  id: string;
  slug: string;
  name: string;
  shortName: string;
  aliases: string[];
  kind: "peptide";
  compoundId?: string;
  functionClass: CompoundFunctionClass;
  functionLabel: string;
  headline: string;
  summary: string;
  primaryGoals: string[];
  mechanism: string;
  considerations: string[];
  overlapSignals: string[];
  sideEffectSignals: string[];
  quickFacts: {
    route: string;
    typicalDose: string;
    frequency: string;
    cycle: string;
    storage: string;
    halfLife: string;
  };
  pharmacokinetics?: {
    halfLifeHours?: number;
    halfLifeLabel?: string;
    confidence?: PharmacokineticConfidence;
  };
  researchLinks: Array<{ label: string; href: string }>;
  source: {
    label: string;
    href: string;
    lastReviewed: string;
    status: LibrarySourceStatus;
  };
}

export interface PepPediaImportMapping {
  compoundIdBySlug: Record<string, string>;
  functionClassBySlug: Record<string, CompoundFunctionClass>;
  shortNameBySlug: Record<string, string>;
  headlineBySlug: Record<string, string>;
  halfLifeOverridesBySlug: Record<
    string,
    {
      halfLifeLabel: string;
      halfLifeHours?: number;
      confidence?: PharmacokineticConfidence;
    }
  >;
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const repoRoot = path.resolve(__dirname, "..", "..");
export const librarySeedPath = path.join(repoRoot, "scripts", "data", "protocol-library.seed.json");
export const libraryImportPath = path.join(repoRoot, "scripts", "data", "protocol-library.import.json");
export const libraryImportReportPath = path.join(repoRoot, "scripts", "data", "protocol-library.import.report.json");
export const libraryMappingPath = path.join(repoRoot, "scripts", "data", "peppedia-import.map.json");
export const libraryGeneratedPath = path.join(repoRoot, "artifacts", "protocol", "src", "data", "library.generated.ts");

export function assertString(value: unknown, field: string) {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new Error(`Expected ${field} to be a non-empty string.`);
  }
}

export function assertOptionalNumber(value: unknown, field: string) {
  if (value !== undefined && (typeof value !== "number" || Number.isNaN(value))) {
    throw new Error(`Expected ${field} to be a valid number when present.`);
  }
}

export function assertStringArray(value: unknown, field: string) {
  if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) {
    throw new Error(`Expected ${field} to be an array of strings.`);
  }
}

export function normalizeLibraryEntries(entries: SeedLibraryEntry[]): SeedLibraryEntry[] {
  return [...entries].sort((a, b) => a.name.localeCompare(b.name));
}

export function formatGeneratedLibrary(entries: SeedLibraryEntry[]) {
  return `import type { LibraryEntry } from "@/data/library-schema";

// This file is generated by scripts/src/generate-library.ts.
// Edit scripts/data/protocol-library.seed.json and regenerate instead.
export const LIBRARY_ENTRIES: LibraryEntry[] = ${JSON.stringify(normalizeLibraryEntries(entries), null, 2)};
`;
}

export function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function uniqueStrings(values: string[]) {
  return Array.from(new Set(values.map((value) => value.trim()).filter(Boolean)));
}

export function pickFirstNonEmpty(...values: Array<string | undefined>) {
  return values.find((value) => typeof value === "string" && value.trim().length > 0)?.trim();
}

export function validateLibraryEntry(entry: unknown, index: number): asserts entry is SeedLibraryEntry {
  if (typeof entry !== "object" || entry === null) {
    throw new Error(`Entry ${index} must be an object.`);
  }

  const record = entry as Record<string, unknown>;
  assertString(record.id, `entries[${index}].id`);
  assertString(record.slug, `entries[${index}].slug`);
  assertString(record.name, `entries[${index}].name`);
  assertString(record.shortName, `entries[${index}].shortName`);
  assertStringArray(record.aliases, `entries[${index}].aliases`);
  assertString(record.kind, `entries[${index}].kind`);
  assertString(record.functionClass, `entries[${index}].functionClass`);
  assertString(record.functionLabel, `entries[${index}].functionLabel`);
  assertString(record.headline, `entries[${index}].headline`);
  assertString(record.summary, `entries[${index}].summary`);
  assertStringArray(record.primaryGoals, `entries[${index}].primaryGoals`);
  assertString(record.mechanism, `entries[${index}].mechanism`);
  assertStringArray(record.considerations, `entries[${index}].considerations`);
  assertStringArray(record.overlapSignals, `entries[${index}].overlapSignals`);
  assertStringArray(record.sideEffectSignals, `entries[${index}].sideEffectSignals`);

  const quickFacts = record.quickFacts as Record<string, unknown> | undefined;
  if (!quickFacts) {
    throw new Error(`entries[${index}].quickFacts is required.`);
  }
  assertString(quickFacts.route, `entries[${index}].quickFacts.route`);
  assertString(quickFacts.typicalDose, `entries[${index}].quickFacts.typicalDose`);
  assertString(quickFacts.frequency, `entries[${index}].quickFacts.frequency`);
  assertString(quickFacts.cycle, `entries[${index}].quickFacts.cycle`);
  assertString(quickFacts.storage, `entries[${index}].quickFacts.storage`);
  assertString(quickFacts.halfLife, `entries[${index}].quickFacts.halfLife`);

  const pharmacokinetics = record.pharmacokinetics as Record<string, unknown> | undefined;
  if (pharmacokinetics) {
    if (pharmacokinetics.halfLifeLabel !== undefined) {
      assertString(pharmacokinetics.halfLifeLabel, `entries[${index}].pharmacokinetics.halfLifeLabel`);
    }
    assertOptionalNumber(pharmacokinetics.halfLifeHours, `entries[${index}].pharmacokinetics.halfLifeHours`);
    if (pharmacokinetics.confidence !== undefined) {
      assertString(pharmacokinetics.confidence, `entries[${index}].pharmacokinetics.confidence`);
    }
  }

  const researchLinks = record.researchLinks;
  if (!Array.isArray(researchLinks)) {
    throw new Error(`entries[${index}].researchLinks must be an array.`);
  }
  researchLinks.forEach((link, linkIndex) => {
    if (typeof link !== "object" || link === null) {
      throw new Error(`entries[${index}].researchLinks[${linkIndex}] must be an object.`);
    }
    const linkRecord = link as Record<string, unknown>;
    assertString(linkRecord.label, `entries[${index}].researchLinks[${linkIndex}].label`);
    assertString(linkRecord.href, `entries[${index}].researchLinks[${linkIndex}].href`);
  });

  const source = record.source as Record<string, unknown> | undefined;
  if (!source) {
    throw new Error(`entries[${index}].source is required.`);
  }
  assertString(source.label, `entries[${index}].source.label`);
  assertString(source.href, `entries[${index}].source.href`);
  assertString(source.lastReviewed, `entries[${index}].source.lastReviewed`);
  assertString(source.status, `entries[${index}].source.status`);
}

export function validateLibraryEntries(entries: unknown): SeedLibraryEntry[] {
  if (!Array.isArray(entries)) {
    throw new Error("Library file must contain an array.");
  }

  entries.forEach((entry, index) => validateLibraryEntry(entry, index));

  const seenIds = new Set<string>();
  const seenSlugs = new Set<string>();

  for (const entry of entries) {
    if (seenIds.has(entry.id)) {
      throw new Error(`Duplicate id: ${entry.id}`);
    }
    if (seenSlugs.has(entry.slug)) {
      throw new Error(`Duplicate slug: ${entry.slug}`);
    }
    seenIds.add(entry.id);
    seenSlugs.add(entry.slug);
  }

  return entries;
}

export async function readJsonFile<T>(filePath: string): Promise<T> {
  const raw = await readFile(filePath, "utf8");
  return JSON.parse(raw) as T;
}

export async function writeJsonFile(filePath: string, value: unknown) {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

export async function loadLibrarySeed() {
  return validateLibraryEntries(await readJsonFile<unknown>(librarySeedPath));
}

export async function loadLibraryImport() {
  return validateLibraryEntries(await readJsonFile<unknown>(libraryImportPath));
}

export async function loadImportMapping() {
  return readJsonFile<PepPediaImportMapping>(libraryMappingPath);
}
